dist: trusty

language: python

env: [OMP_NUM_THREADS=4]

install: [
  "pip install --upgrade cmake",
  "cmake --version",
  "g++ --version",
]

before_script: [
  "cd ${TRAVIS_BUILD_DIR}",
  "ls -Al",
  "mkdir build",
  "cd build",
]

matrix:
  include:
  #  - os: linux
  #    env: CXX='g++-6'
  #    addons: {apt: {packages: [g++-6], sources: [ubuntu-toolchain-r-test]}}

  - os: linux
    env: CXX='g++-7'
    addons: {apt: {packages: [g++-7, ocl-icd-opencl-dev, beignet], sources: [ubuntu-toolchain-r-test], update: true}}

  - os: linux
    env: CXX='g++-8'
    addons: {apt: {packages: [g++-8, ocl-icd-opencl-dev, beignet], sources: [ubuntu-toolchain-r-test], update: true}}

script: [
  "cmake -DCMAKE_BUILD_TYPE=RELEASE ..",
  "cmake --build .",
]
