#dist: xenial
#
#language: cpp
dist: trusty
language: python

env: [OMP_NUM_THREADS=4]

install: [
  "pip install --upgrade cmake",
  "cmake --version",
  "g++ --version",
]

before_script: [
  "cd ${TRAVIS_BUILD_DIR}",
  "ls -Al",
  "mkdir build",
  "cd build",
]

matrix:
  include:
  #  - os: linux
  #    env: CXX='g++-6'
  #    addons: {apt: {packages: [g++-6], sources: [ubuntu-toolchain-r-test]}}

  #  - os: linux
  #    env: CXX='g++-7'  # Doesn't support <filesystem>
  #    addons: {apt: {packages: [g++-7, ocl-icd-opencl-dev, beignet], sources: [ubuntu-toolchain-r-test], update: true}}

  - os: linux
    env: CXX='g++-8'
    addons: {apt: {packages: [g++-8, ocl-icd-opencl-dev, pocl],
                   sources: [ubuntu-toolchain-r-test],
                   update: true}}

#  - os: linux  # TODO: fix compiling with clang
#    env: CXX='clang++-6.0'
#    addons: {apt: {packages: [clang-6.0, libstdc++-7-dev, ocl-icd-opencl-dev, beignet],
#                   sources: [ubuntu-toolchain-r-test, llvm-toolchain-trusty-6.0],
#                   update: true}}

#  - os: osx
#    osx_image: xcode10.1
#    env: brew install gcc && CC=gcc-8 && CXX=g++-8

script: [
  "cmake -DCMAKE_BUILD_TYPE=RELEASE ..",
  "cmake --build .",
  "ctest",
]
